--<ScriptOptions statementTerminator=";"/>

CREATE TABLE ARCO (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NODOPARTENZAID INTEGER NOT NULL,
		NODOARRIVOID INTEGER NOT NULL,
		MAPPAID INTEGER NOT NULL
	);

CREATE TABLE MAPPA (
		PIANO INTEGER NOT NULL,
		PIANTINA VARCHAR(20),
		STATOEMERGENZA INTEGER DEFAULT 0
	);

CREATE TABLE NODO (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		BEACONID VARCHAR(20),
		X INTEGER NOT NULL,
		Y INTEGER NOT NULL,
		TIPO INTEGER NOT NULL,
		PIANO INTEGER NOT NULL
	);

CREATE TABLE PESOARCO (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		IDARCO INTEGER NOT NULL,
		IDPESO INTEGER NOT NULL,
		VALORE INTEGER NOT NULL
	);

CREATE TABLE PESO (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		DESCRIZIONE VARCHAR(30),
		PESO INTEGER NOT NULL
	);

CREATE TABLE UTENTE (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		TOKEN VARCHAR(256) NOT NULL
	);

